//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerFeedbackMsg : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlannerFeedback";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public float current_x;
        public float current_y;
        public float percent_complete;

        public PathPlannerFeedbackMsg()
        {
            this.robot_id = 0;
            this.current_x = 0.0f;
            this.current_y = 0.0f;
            this.percent_complete = 0.0f;
        }

        public PathPlannerFeedbackMsg(int robot_id, float current_x, float current_y, float percent_complete)
        {
            this.robot_id = robot_id;
            this.current_x = current_x;
            this.current_y = current_y;
            this.percent_complete = percent_complete;
        }

        public static PathPlannerFeedbackMsg Deserialize(MessageDeserializer deserializer) => new PathPlannerFeedbackMsg(deserializer);

        private PathPlannerFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.current_x);
            deserializer.Read(out this.current_y);
            deserializer.Read(out this.percent_complete);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.current_x);
            serializer.Write(this.current_y);
            serializer.Write(this.percent_complete);
        }

        public override string ToString()
        {
            return "PathPlannerFeedbackMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\ncurrent_x: " + current_x.ToString() +
            "\ncurrent_y: " + current_y.ToString() +
            "\npercent_complete: " + percent_complete.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
