//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerObstacleSubMsg : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlannerObstacleSub";
        public override string RosMessageName => k_RosMessageName;

        public int x;
        public int y;
        public string type;
        public string id;

        public PathPlannerObstacleSubMsg()
        {
            this.x = 0;
            this.y = 0;
            this.type = "";
            this.id = "";
        }

        public PathPlannerObstacleSubMsg(int x, int y, string type, string id)
        {
            this.x = x;
            this.y = y;
            this.type = type;
            this.id = id;
        }

        public static PathPlannerObstacleSubMsg Deserialize(MessageDeserializer deserializer) => new PathPlannerObstacleSubMsg(deserializer);

        private PathPlannerObstacleSubMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.type);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.type);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "PathPlannerObstacleSubMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\ntype: " + type.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
