//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerResponseMsg : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlannerResponse";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public float[] path_x;
        public float[] path_y;
        public bool success;

        public PathPlannerResponseMsg()
        {
            this.robot_id = 0;
            this.path_x = new float[0];
            this.path_y = new float[0];
            this.success = false;
        }

        public PathPlannerResponseMsg(int robot_id, float[] path_x, float[] path_y, bool success)
        {
            this.robot_id = robot_id;
            this.path_x = path_x;
            this.path_y = path_y;
            this.success = success;
        }

        public static PathPlannerResponseMsg Deserialize(MessageDeserializer deserializer) => new PathPlannerResponseMsg(deserializer);

        private PathPlannerResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.path_x, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.path_y, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.WriteLength(this.path_x);
            serializer.Write(this.path_x);
            serializer.WriteLength(this.path_y);
            serializer.Write(this.path_y);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "PathPlannerResponseMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\npath_x: " + System.String.Join(", ", path_x.ToList()) +
            "\npath_y: " + System.String.Join(", ", path_y.ToList()) +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
