//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ObstacleManager
{
    [Serializable]
    public class ObstacleManagerSubscriberMsg : Message
    {
        public const string k_RosMessageName = "obstacle_manager/ObstacleManagerSubscriber";
        public override string RosMessageName => k_RosMessageName;

        public int x;
        public int y;
        public string type;

        public ObstacleManagerSubscriberMsg()
        {
            this.x = 0;
            this.y = 0;
            this.type = "";
        }

        public ObstacleManagerSubscriberMsg(int x, int y, string type)
        {
            this.x = x;
            this.y = y;
            this.type = type;
        }

        public static ObstacleManagerSubscriberMsg Deserialize(MessageDeserializer deserializer) => new ObstacleManagerSubscriberMsg(deserializer);

        private ObstacleManagerSubscriberMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "ObstacleManagerSubscriberMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
