//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RobotManager
{
    [Serializable]
    public class RobotManagerRobotSubscriberMsg : Message
    {
        public const string k_RosMessageName = "robot_manager/RobotManagerRobotSubscriber";
        public override string RosMessageName => k_RosMessageName;

        public string state;

        public RobotManagerRobotSubscriberMsg()
        {
            this.state = "";
        }

        public RobotManagerRobotSubscriberMsg(string state)
        {
            this.state = state;
        }

        public static RobotManagerRobotSubscriberMsg Deserialize(MessageDeserializer deserializer) => new RobotManagerRobotSubscriberMsg(deserializer);

        private RobotManagerRobotSubscriberMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "RobotManagerRobotSubscriberMsg: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
