//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RobotManager
{
    [Serializable]
    public class RobotManagerRobotPublisherMsg : Message
    {
        public const string k_RosMessageName = "robot_manager/RobotManagerRobotPublisher";
        public override string RosMessageName => k_RosMessageName;

        public int robot_id;
        public string robot_type;
        public float move_speed;
        public float perception_radius;
        public float obstacle_distance_threshold;
        public float start_x;
        public float start_y;
        public float end_x;
        public float end_y;
        public float[] path_x;
        public float[] path_y;
        public bool loop;

        public RobotManagerRobotPublisherMsg()
        {
            this.robot_id = 0;
            this.robot_type = "";
            this.move_speed = 0.0f;
            this.perception_radius = 0.0f;
            this.obstacle_distance_threshold = 0.0f;
            this.start_x = 0.0f;
            this.start_y = 0.0f;
            this.end_x = 0.0f;
            this.end_y = 0.0f;
            this.path_x = new float[0];
            this.path_y = new float[0];
            this.loop = false;
        }

        public RobotManagerRobotPublisherMsg(int robot_id, string robot_type, float move_speed, float perception_radius, float obstacle_distance_threshold, float start_x, float start_y, float end_x, float end_y, float[] path_x, float[] path_y, bool loop)
        {
            this.robot_id = robot_id;
            this.robot_type = robot_type;
            this.move_speed = move_speed;
            this.perception_radius = perception_radius;
            this.obstacle_distance_threshold = obstacle_distance_threshold;
            this.start_x = start_x;
            this.start_y = start_y;
            this.end_x = end_x;
            this.end_y = end_y;
            this.path_x = path_x;
            this.path_y = path_y;
            this.loop = loop;
        }

        public static RobotManagerRobotPublisherMsg Deserialize(MessageDeserializer deserializer) => new RobotManagerRobotPublisherMsg(deserializer);

        private RobotManagerRobotPublisherMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.robot_type);
            deserializer.Read(out this.move_speed);
            deserializer.Read(out this.perception_radius);
            deserializer.Read(out this.obstacle_distance_threshold);
            deserializer.Read(out this.start_x);
            deserializer.Read(out this.start_y);
            deserializer.Read(out this.end_x);
            deserializer.Read(out this.end_y);
            deserializer.Read(out this.path_x, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.path_y, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.loop);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.robot_type);
            serializer.Write(this.move_speed);
            serializer.Write(this.perception_radius);
            serializer.Write(this.obstacle_distance_threshold);
            serializer.Write(this.start_x);
            serializer.Write(this.start_y);
            serializer.Write(this.end_x);
            serializer.Write(this.end_y);
            serializer.WriteLength(this.path_x);
            serializer.Write(this.path_x);
            serializer.WriteLength(this.path_y);
            serializer.Write(this.path_y);
            serializer.Write(this.loop);
        }

        public override string ToString()
        {
            return "RobotManagerRobotPublisherMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\nrobot_type: " + robot_type.ToString() +
            "\nmove_speed: " + move_speed.ToString() +
            "\nperception_radius: " + perception_radius.ToString() +
            "\nobstacle_distance_threshold: " + obstacle_distance_threshold.ToString() +
            "\nstart_x: " + start_x.ToString() +
            "\nstart_y: " + start_y.ToString() +
            "\nend_x: " + end_x.ToString() +
            "\nend_y: " + end_y.ToString() +
            "\npath_x: " + System.String.Join(", ", path_x.ToList()) +
            "\npath_y: " + System.String.Join(", ", path_y.ToList()) +
            "\nloop: " + loop.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
