//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerResult : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlanner";
        public override string RosMessageName => k_RosMessageName;

        public int[] path_x;
        public int[] path_y;

        public PathPlannerResult()
        {
            this.path_x = new int[0];
            this.path_y = new int[0];
        }

        public PathPlannerResult(int[] path_x, int[] path_y)
        {
            this.path_x = path_x;
            this.path_y = path_y;
        }

        public static PathPlannerResult Deserialize(MessageDeserializer deserializer) => new PathPlannerResult(deserializer);

        private PathPlannerResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.path_x, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.path_y, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.path_x);
            serializer.Write(this.path_x);
            serializer.WriteLength(this.path_y);
            serializer.Write(this.path_y);
        }

        public override string ToString()
        {
            return "PathPlannerResult: " +
            "\npath_x: " + System.String.Join(", ", path_x.ToList()) +
            "\npath_y: " + System.String.Join(", ", path_y.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
