//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerFeedback : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlanner";
        public override string RosMessageName => k_RosMessageName;

        public int current_x;
        public int current_y;
        public float percent_complete;

        public PathPlannerFeedback()
        {
            this.current_x = 0;
            this.current_y = 0;
            this.percent_complete = 0.0f;
        }

        public PathPlannerFeedback(int current_x, int current_y, float percent_complete)
        {
            this.current_x = current_x;
            this.current_y = current_y;
            this.percent_complete = percent_complete;
        }

        public static PathPlannerFeedback Deserialize(MessageDeserializer deserializer) => new PathPlannerFeedback(deserializer);

        private PathPlannerFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_x);
            deserializer.Read(out this.current_y);
            deserializer.Read(out this.percent_complete);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_x);
            serializer.Write(this.current_y);
            serializer.Write(this.percent_complete);
        }

        public override string ToString()
        {
            return "PathPlannerFeedback: " +
            "\ncurrent_x: " + current_x.ToString() +
            "\ncurrent_y: " + current_y.ToString() +
            "\npercent_complete: " + percent_complete.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
