//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PathPlanner
{
    [Serializable]
    public class PathPlannerGoal : Message
    {
        public const string k_RosMessageName = "path_planner/PathPlanner";
        public override string RosMessageName => k_RosMessageName;

        public int start_x;
        public int start_y;
        public int end_x;
        public int end_y;

        public PathPlannerGoal()
        {
            this.start_x = 0;
            this.start_y = 0;
            this.end_x = 0;
            this.end_y = 0;
        }

        public PathPlannerGoal(int start_x, int start_y, int end_x, int end_y)
        {
            this.start_x = start_x;
            this.start_y = start_y;
            this.end_x = end_x;
            this.end_y = end_y;
        }

        public static PathPlannerGoal Deserialize(MessageDeserializer deserializer) => new PathPlannerGoal(deserializer);

        private PathPlannerGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start_x);
            deserializer.Read(out this.start_y);
            deserializer.Read(out this.end_x);
            deserializer.Read(out this.end_y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start_x);
            serializer.Write(this.start_y);
            serializer.Write(this.end_x);
            serializer.Write(this.end_y);
        }

        public override string ToString()
        {
            return "PathPlannerGoal: " +
            "\nstart_x: " + start_x.ToString() +
            "\nstart_y: " + start_y.ToString() +
            "\nend_x: " + end_x.ToString() +
            "\nend_y: " + end_y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
